packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - cpu-features
  - esbuild
  - protobufjs
  - sharp
  - ssh2

allowBuilds:
  argon2: true
  cpu-features: false
  esbuild: false
  protobufjs: false
  sharp: false
  ssh2: false
