/** Shared Pino/Fastify logger defaults. Values are redacted structurally. */
export const API_LOGGER_OPTIONS = {
  redact: {
    paths: [
      "req.headers.authorization",
      "req.headers.cookie",
      "res.headers.set-cookie",
      "authorization",
      "cookie",
      "setCookie",
      "password",
      "passwordHash",
      "token",
      "accessToken",
      "refreshToken",
      "B2_APPLICATION_KEY",
      "B2_KEY_ID",
      "STORAGE_PROFILE_MASTER_KEY",
      "encryptedApplicationKey",
      "b2ApplicationKey",
      "CLOUDFLARE_PROVISIONING_API_TOKEN",
      "CLOUDFLARE_CACHE_RULES_API_TOKEN",
      "CLOUDFLARE_PURGE_API_TOKEN",
      "DATABASE_URL",
      "REDIS_URL",
      "presignedUrl",
      "presignedUrls",
    ],
    censor: "[REDACTED]",
  },
};
